name: Illustrate no update check
on:
  push:
    paths:
      - '.github/workflows/illustrate-update-check.yml'
      - 'mwe.tex'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  miktex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add ~/bin to PATH
        run: echo "${HOME}/bin" >> $GITHUB_PATH
      - name: "Install MikTeX: apt-get install"
        run: |
          set -e
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/miktex.gpg] https://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt-get update -y -q
          sudo apt-get install -qq -y --no-install-recommends miktex
      - run: sudo miktexsetup --admin --verbose finish
      - run: sudo initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
      - run: sudo miktex --admin --verbose packages update-package-database
      - run: sudo miktex --admin --verbose packages update
      - run: miktex --verbose packages update
      - run: sudo miktex --admin --verbose packages install cm-super
      - run: sudo miktex --admin --verbose fndb refresh
      - run: sudo initexmf --admin --verbose --update-fndb
      - run: sudo initexmf --admin --verbose --mklinks --force
      - run: sudo updmap
      - run: pdflatex mwe
