name: MiKTeX (Windows)
on:
  push:
    paths:
      - '.github/workflows/miktex-windows.yml'
      - 'example-expansion.tex'
      - 'example-expansion-T1.tex'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  miktex:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        filename: [example-expansion.tex, example-expansion-T1.tex]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MiKTeX
        run: |
          choco install miktex
          Import-Module "$env:ProgramData\chocolatey\helpers\chocolateyInstaller.psm1"; Update-SessionEnvironment
      - name: Update MiKTeX packages
        run: |
          initexmf --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --verbose packages update-package-database
          miktex --verbose packages update
          miktex --verbose packages install cm-super
          miktex --verbose fndb refresh
          initexmf --verbose --update-fndb
          initexmf --verbose --mklinks --force
          updmap
      - run: pdflatex ${{ matrix.filename }}
