name: MiKTeX (Windows)
on:
  push:
    paths:
      - '.github/workflows/miktex-windows.yml'
      - 'example-expansion.tex'
      - 'example-expansion-T1.tex'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  miktex:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        filename: [example-expansion.tex, example-expansion-T1.tex]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MiKTeX
        run: |
          choco install miktex --no-progress
          echo "C:\Program Files\MiKTeX\miktex\bin\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
      - name: Configure MiKTeX
        run: |
          initexmf --admin --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --admin --verbose packages update-package-database
          miktex --admin --verbose packages update
          miktex --verbose packages update
          miktex --admin --verbose packages install cm-super
          miktex --admin --verbose fndb refresh
          initexmf --admin --verbose --update-fndb
          initexmf --admin --verbose --mklinks --force
          updmap --admin
      - run: pdflatex ${{ matrix.filename }}
