name: MiKTeX (Linux)
on:
  push:
    paths:
      - '.github/workflows/miktex-linux.yml'
      - 'example-expansion.tex'
      - 'example-expansion-T1.tex'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  miktex:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        filename: [example-expansion.tex, example-expansion-T1.tex]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add ~/bin to PATH
        run: echo "${HOME}/bin" >> $GITHUB_PATH
      - name: "Install MikTeX: apt-get install"
        run: |
          set -e
          sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/miktex.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/miktex.gpg] https://miktex.org/download/ubuntu jammy universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt-get update -y -q
          sudo apt-get install -qq -y --no-install-recommends miktex
      - name: Install texlive-fonts-recommended
        run: |
          set -e
          sudo apt-get install -y -q equivs
          equivs-build tex-common.control
          sudo dpkg -i tex-common_9999_all.deb
          equivs-build texlive-base.control
          sudo dpkg -i texlive-base_9999_all.deb
          sudo cp -a update-texmf-config /usr/bin
          ls -la /usr/bin/update-texmf-config
          update-texmf-config
          sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
      - run: miktexsetup --verbose finish
      - run: initexmf --verbose --set-config-value=[MPM]AutoInstall=1
      - run: miktex --verbose packages update-package-database
      - run: miktex --verbose packages update
      - run: miktex --verbose packages update
      - run: miktex --verbose packages install cm-super
      - run: miktex --verbose fndb refresh
      - run: initexmf --verbose --update-fndb
      - run: initexmf --verbose --mklinks --force
      - run: updmap
      - run: pdflatex ${{ matrix.filename }}
