name: MiKTeX (Windows)
on:
  push:
    paths:
      - '.github/workflows/miktex-windows.yml'
      - 'example-expansion.tex'
      - 'example-expansion-T1.tex'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  miktex:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        filename: [example-expansion.tex, example-expansion-T1.tex]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MiKTeX
        shell: cmd
        run: |
          choco install miktex --no-progress
      - name: Update MiKTeX packages
        shell: cmd
        run: |
          call refreshenv
          initexmf --verbose --set-config-value=[MPM]AutoInstall=1
          miktex --verbose packages update-package-database
          miktex --verbose packages update
          miktex --verbose packages install cm-super
          miktex --verbose fndb refresh
          initexmf --verbose --update-fndb
          type C:\Users\runneradmin\AppData\Local\MiKTeX\miktex\log\initexmf.log
          initexmf --verbose --mklinks --force
          type C:\Users\runneradmin\AppData\Local\MiKTeX\miktex\log\initexmf.log
          updmap
      - name: pdflatex
        shell: cmd
        run: |
          call refreshenv
          pdflatex ${{ matrix.filename }}
